var elements = (function () {
	return {
		companyNameInput: document.querySelector('.company-name-input'),
		startButton: document.querySelector('.start'),
		stopButton: document.querySelector('.stop'),
		easyButton: document.querySelector('.easy'),
		mediumButton: document.querySelector('.medium'),
		hardButton: document.querySelector('.hard'),
		timeDiv: document.querySelector('.time'),
		budgetDiv: document.querySelector('.budget'),
		addProjectButton: document.querySelector('.add-project'),
		projectNameInput: document.querySelector('.project-name-input'),
		addManagerButton: document.querySelector('.add-manager'),
		managerNameInput: document.querySelector('.manager-name-input'),
		managerSurnameInput: document.querySelector('.manager-surname-input'),
		managerExperienceInput: document.querySelector('.manager-experience-input'),
		developerNameInput: document.querySelector('.developer-name-input'),
		developerSurnameInput: document.querySelector('.developer-surname-input'),
		developerExperienceInput: document.querySelector('.developer-experience-input'),
		addDeveloperButton: document.querySelector('.add-developer'),
		userProjects: document.querySelector('.user-projects'),
		userManagers: document.querySelector('.user-managers'),
		userDevelopers: document.querySelector('.user-developers'),
	}
})();